openapi: 3.1.0
info:
    title: TODO API
    description: Application Interface Definition
    version: 0.0.1

servers:
    - url: http://localhost:8080
      description: local server

paths:
    /backlog:
        get:
            summary: Get backlog
            operationId: getBacklog
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/BacklogResponse"
components:
    schemas:
        BacklogResponse:
            $ref: "./schemas/features/backlog/BacklogResponse.yml"
        InternalServerError:
            $ref: "./schemas/error/InternalServerError.yml"

    responses:
        InternalServerError:
            description: Internal Server Error
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/InternalServerError"
