spring:
    datasource:
        url: jdbc:mysql://localhost:3306/todo?serverTimezone=Asia/Tokyo
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver

    jooq:
        sql-dialect: MYSQL

logging:
    level:
        org.jooq.tools.LoggerListener: info
