version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: todo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
      MYSQL_USER: local_user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - todo-mysql:/var/lib/mysql

volumes:
  todo-mysql:
    name: todo-mysql
